### ISSUE TITLE
PTR record type creates incorrect value

### ISSUE THREAD

**Issue by pgeorgopoulos** [mskarbek/ansible-nsupdate#10]
When I use the nsupdate module to create a PTR record, it always creates the record so the value of the record is <whatever_I_set>.<zone_name>.

Specific example:
- name: Add PTR record
  nsupdate:
    server: "nsServer"
    zone: "10.in-addr.arpa."
    record: "102.100.1"
    value: "ansible-test.nsServer"
    type: PTR
    state: present

Creates the record as expected except 10.1.100.102.in-addr.arpa points to ansible-test.nsServer.10.in-addr.arpa. instead of ansible-test.nsServer.

**Comment by andreaso** [comment]
I would say that that is normal/expected DNS behavior.

If you the value to be an absolute name you need to add a dot at the end.

    value: "ansible-test.nsServer."

**Comment by pgeorgopoulos** [comment]
Thanks for the quick feedback. 
That works and shows clearly my misunderstanding.
One character sure can have a big impact.
